name: After merge build

on:
  push:
    branches:
      - master
      - main
      - trunk
      - develop
      - maine
      - mane
  schedule:
    - cron: '0 3 * * 1,4'

jobs:
  build:
    env:
      github_token: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Cache .gradle
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: jdk11
          gradle-distribution-sha-256-sum-warning: false

      - run: ./gradlew assembleRelease

      - run: ./gradlew publishReleasePublicationToGithubRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}

      - run: ./gradlew projectCoverage

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - uses: actions/cache@v2
        name: Upload base (release)
        with:
          path: diffuse-source-file-release
          key: diffuse-${{ github.sha }}-${{ hashFiles('**/aar/**.aar') }}

      - run: cp slidr/build/outputs/aar/library-release.apk diffuse-source-file-release
        shell: bash
