name: Build project

on:
  pull_request:

jobs:
  cancel-previous-workflows:
    name: Cancel previous workflow runs
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Code style check
        uses: gradle/gradle-build-action@v2
        with:
          arguments: projectCodestyle
          dependencies-cache-enabled: true

      - name: Assemble
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble
          dependencies-cache-enabled: true

      - name: Unit tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: projectCoverage
          dependencies-cache-enabled: true

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Android Lint
        uses: gradle/gradle-build-action@v2
        with:
          arguments: projectLint
          dependencies-cache-enabled: true

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: lint-results
          path: '${{ github.workspace }}/**/build/**/reports/lint-results-*.html'
